name = "Chunklock Extended"
author = "Kacper0510, SzeMrok"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cadfef517a8f7e23a5d8f94192241013244e6aaec9ab9888909e9094e2389966"

[versions]
forge = "47.2.4"
minecraft = "1.20.1"
